# Generated by Django 3.2.5 on 2022-04-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, height_field=100, upload_to='avatars', width_field=100),
        ),
    ]
