# Generated by Django 3.2.5 on 2022-04-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_sports',
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_sports',
            field=models.ManyToManyField(related_name='favorite_sports', to='sports.Sport'),
        ),
    ]
