# Generated by Django 3.2.5 on 2022-06-04 17:45

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2022, 6, 4)), django.core.validators.MaxValueValidator(datetime.date(2022, 7, 4))]),
        ),
    ]
