# Generated by Django 3.2.5 on 2022-05-30 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ground',
            old_name='latitide',
            new_name='latitude',
        ),
    ]
